DROP DATABASE IF EXISTS jfc7xbeltcv5wz1h;
CREATE DATABASE jfc7xbeltcv5wz1h;
USE jfc7xbeltcv5wz1h;

CREATE TABLE burgers
(
	id int NOT NULL AUTO_INCREMENT,
	burger_name varchar(255) NOT NULL,
	devoured BOOLEAN DEFAULT false,$ heroku config:set NPM_CONFIG_PRODUCTION=false
  	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	PRIMARY KEY(id)
);